services:
  tdns-stats:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./config.yml:/etc/tdns-stats/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/tdns-stats/docker-compose.yml:/app/docker-compose.yml
    restart: unless-stopped
